---
title: "R Notebook"
output: html_notebook
---


```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
```

```{r}

# Lire les données de l'étude 1 à partir du fichier "etude1.csv"
etude1 <- read.csv("etude1.csv")

# Lire les données de l'étude 2 à partir du fichier "etude2.csv"
etude2 <- read.csv("etude2.csv")

# Lire les données de l'étude 3 à partir du fichier "etude3.csv"
etude3 <- read.csv("etude3.csv")

```

```{r}


# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"


```


```{r}
# Combinez les données de toutes les études en un seul dataframe
data <- rbind(etude1, etude2, etude3)

```

```{r}

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Afficher les résultats
summary(model)
```


```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",",dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",",dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",",dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
data <- rbind(etude1, etude2, etude3)

# Convertir les variables catégorielles en facteurs
data$Expertise <- factor(data$Expertise)
data$Complexite <- factor(data$Complexite)

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Afficher les résultats
summary(model)

```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
data <- rbind(etude1, etude2, etude3)

# Convertir les variables catégorielles en facteurs
data$Expertise <- factor(data$Expertise)
data$Complexite <- factor(data$Complexite)

# Convertir la variable de réponse en type numérique
data$Tps_Tot <- as.numeric(as.character(data$Tps_Tot))

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Afficher les résultats
summary(model)

```

```{r}
write.csv(data, "data_meta.csv", row.names = TRUE)
```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
data <- rbind(etude1, etude2, etude3)

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Afficher les résultats
summary(model)

summary_table <- summary(model)$coefficients
p_values <- summary_table[, "Pr(>|t|)"]
cat("\n")
cat("P-values:\n")
print(p_values)
```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
# Charger le package "lmerTest" pour obtenir les p-values
library(lmerTest)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
data <- rbind(etude1, etude2, etude3)

# Effectuer la régression hiérarchique multiniveau
model1 <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Afficher les résultats avec les p-values
summary_table <- coef(summary(model))
p_values <- summary_table[, "Pr(>|t|)"]
summary(model)
cat("\n")
cat("P-values:\n")
print(p_values)

```
```{r}
# Charger les packages nécessaires
library(lme4)
library(ggplot2)

# ...

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Obtenir les résidus standardisés
residuals <- resid(model, type = "pearson") # Utiliser les résidus standardisés de Pearson

# Visualisation des résidus
ggplot(data, aes(x = fitted(model), y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  xlab("Valeurs prédites") +
  ylab("Résidus standardisés") +
  ggtitle("Diagramme des résidus")

# Visualisation des effets fixes
effects <- data.frame(Effect = rownames(summary(model)$coefficients), 
                      Estimate = fixef(model),
                      Std_Error = sqrt(diag(vcov(model))),
                      stringsAsFactors = FALSE)

ggplot(effects, aes(x = Estimate, y = Effect)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = Estimate - 1.96 * Std_Error, xmax = Estimate + 1.96 * Std_Error), height = 0) +
  xlab("Estimation de l'effet") +
  ylab("Effets fixes") +
  ggtitle("Estimation des effets fixes avec intervalles de confiance à 95%")

# Visualisation de l'effet de la variable Docs en fonction de l'expertise
ggplot(data, aes(x = Docs, y = Tps_Tot, color = Expertise)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  xlab("Docs") +
  ylab("Tps_Tot") +
  ggtitle("Effet de la variable Docs selon l'expertise")

# ...

# Ajoute d'autres visualisations selon tes besoins


```
```{r}
library(plot3D)
scatter3D(data$Docs, data$TG_Tot, data$Tps_Tot, pch = 16,
          xlab = "Docs", ylab = "TG_Tot", zlab = "Tps_Tot",
          main = "Relation entre Docs, TG_Tot et Tps_Tot")

```
```{r}
library(ggplot2)
ggplot(data, aes(x = Docs, y = TG_Tot, fill = Tps_Tot)) +
  geom_tile() +
  scale_fill_gradient(low = "blue", high = "red") +
  xlab("Docs") +
  ylab("TG_Tot") +
  ggtitle("Relation entre Docs, TG_Tot et Tps_Tot")

```
```{r}
library(ggplot2)
ggplot(data, aes(x = Docs, y = TG_Tot, fill = Tps_Tot)) +
  geom_tile() +
  scale_fill_gradient(low = "blue", high = "red") +
  xlab("Docs") +
  ylab("TG_Tot") +
  ggtitle("Relation entre Docs, TG_Tot et Tps_Tot")

```

```{r}
library(ggplot2)
ggplot(data, aes(x = Docs, y = TG_Tot, color = Tps_Tot)) +
  geom_point() +
  xlab("Docs") +
  ylab("TG_Tot") +
  ggtitle("Relation entre Docs, TG_Tot et Tps_Tot")
```

```{r}
# Installer et charger le package "relaimpo"
install.packages("relaimpo")
library(relaimpo)

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Calculer les poids relatifs
rel_imp <- calc.relimp(model)

# Afficher les poids relatifs
print(rel_imp)

```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
# Charger le package "relaimpo" pour les poids relatifs
library(relaimpo)

# Effectuer la régression hiérarchique multiniveau
model <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = data)

# Convertir l'objet de modèle en lmerMod
model_lmerMod <- as(model, "lmerMod")

# Calculer les poids relatifs
rel_imp <- calc.relimp(model_lmerMod)

# Afficher les poids relatifs
print(rel_imp)

```

```{r}
# Charger le package "nlme" pour effectuer la régression linéaire mixte
library(nlme)

# Ajuster le modèle linéaire mixte avec lme()
model_lme <- lme(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise, random = ~1 | Etude, data = data)

# Calculer les coefficients standardisés
coef_std <- coef(model_lme) / sqrt(diag(vcov(model_lme)))

# Afficher les coefficients standardisés
print(coef_std)

```
```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
data2 <- rbind(etude1, etude2, etude3)

# Effectuer la régression hiérarchique multiniveau en tenant compte des effets aléatoires
model2 <- lmer(Tps_Tot ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude) + (1 | Etude:Complexite), data = data2)

# Afficher les résultats
summary(model2)


```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
# Charger le package "lmerTest" pour obtenir les p-values
library(lmerTest)

# Charger les données d'étude
etude2f <- read.table("etu2_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3f <- read.table("etu3_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude2f) <- colnames(etude3f) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot", "FOFG", "FOFD")

# Ajouter une colonne "Etude" aux données de chaque étude
etude2f$Etude <- "Etude 2"
etude3f$Etude <- "Etude 3"

# Combiner les données des trois études
dataf <- rbind(etude2f, etude3f)

# Effectuer la régression hiérarchique multiniveau
modelfd <- lmer(Docs ~ FOFD + Complexite + Expertise + (1 | Etude), data = dataf)

# Afficher les résultats avec les p-values
summary_table <- coef(summary(modelfd))
p_values <- summary_table[, "Pr(>|t|)"]
summary(modelfd)
cat("\n")
cat("P-values:\n")
print(p_values)
```

```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
# Charger le package "lmerTest" pour obtenir les p-values
library(lmerTest)

# Charger les données d'étude
etude2f <- read.table("etu2_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3f <- read.table("etu3_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude2f) <- colnames(etude3f) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot", "FOFG", "FOFD")

# Ajouter une colonne "Etude" aux données de chaque étude
etude2f$Etude <- "Etude 2"
etude3f$Etude <- "Etude 3"

# Combiner les données des trois études
dataf <- rbind(etude2f, etude3f)

# Effectuer la régression hiérarchique multiniveau
modelfg <- lmer(Tps_Tot ~ FOFG + Complexite + Expertise + (1 | Etude), data = dataf)

# Afficher les résultats avec les p-values
summary_table <- coef(summary(modelfg))
p_values <- summary_table[, "Pr(>|t|)"]
summary(modelfg)
cat("\n")
cat("P-values:\n")
print(p_values)
```
```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)
# Charger le package "lmerTest" pour obtenir les p-values
library(lmerTest)

# Charger les données d'étude
etude2TCO <- read.table("etu2_FOF_TCO.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3TCO <- read.table("etu3_FOF_TCO.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude2f) <- colnames(etude3f) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot", "FOFG", "FOFD")

# Ajouter une colonne "Etude" aux données de chaque étude
etude2TCO$Etude <- "Etude 2"
etude3TCO$Etude <- "Etude 3"

# Combiner les données des trois études
dataTCO <- rbind(etude2TCO, etude3TCO)


# Effectuer la régression hiérarchique multiniveau uniquement pour le niveau "TC" de la complexité
model_tc <- lmer(Docs ~ FOFD + Complexite + Expertise + (1 | Etude) + (1 | Etude : Complexite), data = dataTCO)

# Afficher les résultats
summary(model_tc)
```
```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude1 <- read.table("etude1.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude2 <- read.table("etude2.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3 <- read.table("etude3.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude1) <- colnames(etude2) <- colnames(etude3) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot")

# Ajouter une colonne "Etude" aux données de chaque étude
etude1$Etude <- "Etude 1"
etude2$Etude <- "Etude 2"
etude3$Etude <- "Etude 3"

# Combiner les données des trois études
dataRI <- rbind(etude1, etude2, etude3)

# Effectuer la régression hiérarchique multiniveau
modelRI <- lmer(Tps_RI ~ Docs + TG_Tot + Complexite + Expertise + (1 | Etude), data = dataRI)

# Afficher les résultats
summary(modelRI)

summary_table <- summary(model)$coefficients
p_values <- summary_table[, "Pr(>|t|)"]
cat("\n")
cat("P-values:\n")
print(p_values)
```


```{r}
# Charger le package "lme4" pour effectuer la régression hiérarchique multiniveau
library(lme4)

# Charger les données d'étude
etude2FOFD <- read.table("etu2_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")
etude3FOFD <- read.table("etu3_FOF.csv", header=TRUE, sep=",", dec=".", check.names=TRUE, fileEncoding="latin1")

# Vérifier et ajuster l'ordre et les noms des colonnes si nécessaire
colnames(etude2FOFD) <- colnames(etude3FOFD) <- c("Expertise", "Complexite", "Tps_Tot", "Tps_Xplr", "Tps_Xplo", "Tps_RI", "SW2a", "SW2b", "Docs", "TG_Tot", "FOFG", "FOFD")

# Ajouter une colonne "Etude" aux données de chaque étude
etude2FOFD$Etude <- "Etude 2"
etude3FOFD$Etude <- "Etude 3"

# Combiner les données des trois études
dataFOFD <- rbind(etude2FOFD, etude3FOFD)

# Effectuer la régression hiérarchique multiniveau
modelFOFD <- lmer(Docs ~ FOFD + Complexite + Expertise + (1 | Etude), data = dataFOFD)

# Afficher les résultats
summary(modelFOFD)

summary_table <- summary(modelFOFD)$coefficients
p_values <- summary_table[, "Pr(>|t|)"]
cat("\n")
cat("P-values:\n")
print(p_values)
```